import BottomBar from "../menu/bottom.bar";
import SearchBar from "../menu/search.bar";
import OverlayMenu from "../menu/overlay.menu";
import Footer from "../menu/footer.bar";
import TopBar from "../menu/top.bar";
import {useAppSelector} from "../../redux/store";
import {selectOverlayMenu} from "../../redux/slices/overlayMenuSlice";
import {selectSearch} from "../../redux/slices/searchSlice";
import Sidebar from "../menu/side.bar";
import styled from "styled-components";
import {useLocation} from "react-router-dom";

interface LayoutProps {
    children: React.ReactNode
    title: string
}


const ChildrenWrapper = styled.div`
  & > .search {
    transition: padding-top 0.5s ease-in-out;
    color: #fff;
    padding: 11.5rem 2rem 6.25rem 2rem;

    @media (min-width: 1024px) {
      transition: none;
      padding: 10.6875rem 3.125rem 0 9.1rem;
    }

    @media (min-width: 1280px) {
      transition: none;
      padding: 10.6875rem 3.125rem 0 10.1rem;
    }
  }

  & > .non_search {
    transition: padding-top 0.5s ease-in-out;
    color: #fff;
    padding: 6.25rem 2rem 6.25rem 2rem;

    @media (min-width: 1024px) {
      transition: none;
      padding: 10.6875rem 3.125rem 0 9.1rem;
    }

    @media (min-width: 1280px) {
      transition: none;
      padding: 10.6875rem 3.125rem 0 10.1rem;
    }
  }
`;

const Layout = ({children, title}: LayoutProps) => {
    const router = useLocation();
    const overlayMenu = useAppSelector(selectOverlayMenu);
    const search = useAppSelector(selectSearch);

    return (
        <>
            <head>
                <title>Bitfull - {title}</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport"
                      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
                <link rel="icon" href="/logo.svg"/>
            </head>
            <main>
                <TopBar/>
                <Sidebar/>
                <OverlayMenu/>
                <ChildrenWrapper style={{
                    display: overlayMenu ? "none" : ""
                }}>
                    <div className={`${search ? "search" : "non_search"}`}>
                        {children}
                        {!router.pathname.startsWith('/user') && (<Footer/>)}
                    </div>
                </ChildrenWrapper>
                <div style={{
                    opacity: overlayMenu ? "0" : "1",
                    transition: "all 0.5s ease-in-out",
                    userSelect: overlayMenu ? "none" : "auto"
                }}>
                    <SearchBar/>
                </div>
                <BottomBar/>
            </main>
        </>
    );
};

export default Layout;
