import React from 'react';
import Head from "next/head";
import TopBar from "@/components/menu/top.bar";
import Sidebar from "@/components/menu/side.bar";
import BottomBar from "@/components/menu/bottom.bar";
import OverlayMenu from "@/components/menu/overlay.menu";
import {useAppSelector} from "@/redux/store";
import {selectOverlayMenu} from "@/redux/slices/overlayMenuSlice";
import styled from "styled-components";


interface LayoutProps {
    children: React.ReactNode
    title: string
}

const ChildrenWrapper = styled.div`
  padding: 5.25rem 2rem 6.25rem 2rem;

  @media (min-width: 1024px) {
    padding: 11.6875rem 3.125rem 0 9.1rem;
  }

  @media (min-width: 1280px) {
    padding: 11.6875rem 3.125rem 0 10.1rem;
  }
`;

const Layout = ({children, title}: LayoutProps) => {
    const overlayMenu = useAppSelector(selectOverlayMenu);

    return (
        <>
            <Head>
                <title>Bitfull - {title}</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport"
                      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
                <link rel="icon" href="/logo.svg"/>
            </Head>
            <main>
                <TopBar/>
                <Sidebar/>
                <OverlayMenu/>
                <ChildrenWrapper style={{display: overlayMenu ? "none" : ""}}>
                    {children}
                </ChildrenWrapper>
                <BottomBar/>
            </main>
        </>
    );
};

export default Layout;
